{% set version = "10.0.0" %}

package:
  name: faker
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/F/Faker/Faker-{{ version }}.tar.gz
  sha256: 530690ad12a2a054071af95fc8a354c5fd57b5e7707053a9662f40f14a87b68e

build:
  number: 0
  skip: True # [py<36]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - faker = faker.cli:execute_from_command_line

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - python-dateutil >=2.4
    - text-unidecode ==1.3
    - typing-extensions >=3.10.0.2  # [py<38]

test:
  imports:
    - faker
    - faker.cli
    - faker.documentor
    - faker.exceptions
    - faker.factory
    - faker.generator
    - faker.proxy
  requires:
    - pip
  files:
    - run_test.py
  commands:
    - pip check
    - python -m faker --help

about:
  home: https://faker.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Faker is a Python package that generates fake data for you
  description: |
    Faker is a Python package that generates fake data for you.
    Whether you need to bootstrap your database, create good-looking XML documents,
    fill-in your persistence to stress test it, or anonymize data taken from a
    production service, Faker is for you.
  dev_url: https://github.com/joke2k/faker
  doc_url: https://faker.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpafs