{% set version = "4.0.0" %}

package:
  name: faker
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/F/Faker/Faker-{{ version }}.tar.gz
  sha256: 1b1a58961683b30c574520d0c739c4443e0ef6a185c04382e8cc888273dbebed

build:
  entry_points:
    - faker = faker.cli:execute_from_command_line
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
    - pytest-runner
  run:
    - python
    - python-dateutil >=2.4
    - six >=1.10
    - text-unidecode ==1.2
    - ipaddress  # [py27]

test:
  files:
    - run_test.py
  commands:
    - PYTHONIOENCODING=utf8 faker --help  # [not win]
    - SET "PYTHONIOENCODING=utf8" & faker --help  # [win]

about:
  home: https://faker.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Faker is a Python package that generates fake data for you'
  dev_url: https://github.com/joke2k/faker
  doc_url: https://faker.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
