{% set name = "faker" %}
{% set version = "37.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7f69d579588c23d5ce671f3fa872654ede0e67047820255f43a4aa1925b89780

build:
  number: 0
  skip: True # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - faker = faker.cli:execute_from_command_line

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - typing_extensions
    - python-tzdata

test:
  source_files:
    - tests
  imports:
    - faker
    - faker.cli
    - faker.documentor
    - faker.exceptions
    - faker.factory
    - faker.generator
    - faker.proxy
  requires:
    - pip
    - pytest
    - freezegun
    - validators
  commands:
    - pip check
    - python -m faker --help
    - pytest -vv

about:
  home: https://faker.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Faker is a Python package that generates fake data for you
  description: |
    Faker is a Python package that generates fake data for you.
    Whether you need to bootstrap your database, create good-looking XML documents,
    fill-in your persistence to stress test it, or anonymize data taken from a
    production service, Faker is for you.
  dev_url: https://github.com/joke2k/faker
  doc_url: https://faker.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpafs
