{% set version = "4.0.1" %}

package:
  name: faker
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/F/Faker/Faker-{{ version }}.tar.gz
  sha256: 440d68fe0e46c1658b1975b2497abe0c24a7f772e3892253f31e713ffcc48965

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - faker = faker.cli:execute_from_command_line

requirements:
  host:
    - python >=3
    - pip
    - pytest-runner
  run:
    - python >=3
    - python-dateutil >=2.4
    - text-unidecode ==1.3

test:
  files:
    - run_test.py
  commands:
    - PYTHONIOENCODING=utf8 faker --help  # [not win]
    - SET "PYTHONIOENCODING=utf8" & faker --help  # [win]

about:
  home: https://faker.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Faker is a Python package that generates fake data for you'
  dev_url: https://github.com/joke2k/faker
  doc_url: https://faker.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
