{% set name = "Faker" %}
{% set version = "0.7.18" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_val = "310b20f3c497a777622920dca314d90f774028d49c7ee7ccfa96ca4b9d9bf429" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash_val }}


build:
  entry_points:
    - faker=faker.cli:execute_from_command_line

  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - python-dateutil >=2.4
    - six
    - ipaddress  # [py27]

test:
  files:
    - run_test.py
  commands:
    - faker --help  # [osx]
    - PYTHONIOENCODING=utf8 faker --help  # [linux]
    - SET "PYTHONIOENCODING=utf8" & faker --help  # [win]

about:
  home: https://faker.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Faker is a Python package that generates fake data for you.'
  dev_url: https://github.com/joke2k/faker
  doc_url: https://faker.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
