{% set version = "8.8.2" %}

package:
  name: faker
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/F/Faker/Faker-{{ version }}.tar.gz
  sha256: 22534c3aa6d2ef9f38403a234dc9b71b5cb878fb765c72994be5dc7b4eaf0865

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - faker = faker.cli:execute_from_command_line

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - wheel
  run:
    - python >=3.6
    - python-dateutil >=2.4
    - text-unidecode ==1.3

test:
  imports:
    - faker
    - faker.cli
    - faker.documentor
    - faker.exceptions
    - faker.factory
    - faker.generator
    - faker.proxy
  requires:
    - pip
  files:
    - run_test.py
  commands:
    - pip check
    - python -m faker --help
about:
  home: https://faker.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Faker is a Python package that generates fake data for you
  dev_url: https://github.com/joke2k/faker
  doc_url: https://faker.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpafs