{% set name = "faker" %}
{% set version = "40.39.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 52799ad96fcf92aab2fc96a9e03869bbf1a634300f7cd91c38dbfd51f639f6fa

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - faker = faker.cli:execute_from_command_line

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    # tzdata is now required only on Windows, while remaining optional on other platforms
    - python-tzdata  # [win]

# test_iban_stdnum is flaky: some nl_BE bank codes not yet in python-stdnum's registry
{% set tests_to_skip = " or ".join([
    "test_iban_stdnum",
]) %}

test:
  source_files:
    - tests
  imports:
    - faker
    - faker.cli
    - faker.documentor
    - faker.exceptions
    - faker.factory
    - faker.generator
    - faker.proxy
  requires:
    - pip
    - pytest
    - freezegun
    - validators
    - python-stdnum >=1.20
  commands:
    - pip check
    - python -m faker --help
    - pytest -vv -k "not ({{ tests_to_skip }})"

about:
  home: https://faker.readthedocs.io
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Faker is a Python package that generates fake data for you
  description: |
    Faker is a Python package that generates fake data for you.
    Whether you need to bootstrap your database, create good-looking XML documents,
    fill-in your persistence to stress test it, or anonymize data taken from a
    production service, Faker is for you.
  dev_url: https://github.com/joke2k/faker
  doc_url: https://faker.readthedocs.io

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpafs
