appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: cVipnhLFOnytOp6LP8Mo6gLypqhUZsLmA+zRUJ31ZYbCYQV1nNl6eaOl7CFAIf9ZSNWGVOIpXYAmRzFGesdi74WxO0irDNXXPjcdF0Fkn2xkuqkuYgf0xkp4LxpQEFhwBZZjYkrqOwKOAlZdfKDFgNpUIwm9cOyrqtcUmNWqSnz9WGgJoVy+qVuMj3F85zFsWbnPm/CME11Wy6JYoOT1oOOzGB15vr9f7OO1zyzIanT8YQ28RNafuIMNVSBWhVEiBbHC7wQ26iCbJhoT3W4NUaWsmQMmc7v4qZDDx2yIkdBKN3PcqE1NhEJmNFGfyBQu5PcLZwCdk4vmzOXTKlsErIenSXKWlwkSIhnRoZBQOJDmRxdsr2OLDmiC9kVwkvhLrbKSSfZ9t/efmSa5Xt6SXhJP1szsAwpINxYxcue3guRw6D0L5jMvu/9BLB3nlrgp1k8PlZYi4+zta+mbmP/LkZwaTTboDxlYxFdDUsJ8E1ORMLajx6M/xNyCe2PewGt34OwsT14NWVwmsAbq/qTozrO6tMcu1gtF69KmIadjln1Cw/mB0gC8T4h82uy6vNk0YyUVvadnIG/PU1lgZiOfrR2ZTFgt04j7acETGWs5iHDFiFNYh4sfqwDJJSwFh1/NufMcunDD+FNHnkuN6AU4h1LlcG9SqiayD4FF+Zb0o0U=}
provider:
  win: azure
bot:
  automerge: true
conda_forge_output_validation: true
