travis:
  secure:
    BINSTAR_TOKEN: Wx4OVqJrQTW6roUJJlHjK6aeyqMf3DT44mq2o6YkY7y7JyL0bEdACXP7z5jVwZWjxyUW4KLuPPsAZaHIDHO0S1TMyzbiAOt0ZrZy31cykiT8OpQl7Yw7prE49s+bUii9IZgUfqMLArHDjY9VFtF7JE9XBdShsqbkZ2NzVbDBRP8IRlS+TXK5Ujob/YpBKJo/XazLCKJOXobd935bRt918Xl6COrhXnhSVV0EfkDLjYWpOLNz5HVuvW+46uTTz9ZRGcM1Q1RYURHkUgQyjSVPZkTUrEfvWJoh1Kh26s2npnu9hu8iurri+wcp6B/xk8OpFFoEK46b4gdhd82gyxhIEh2eq/rtYgJBTwIs7OstRyBFVvz+VOdxMbnd2y6AAWvY065ee0eeHhz1kCqNFMKo2ATfotb85JnTcEqkBvlNmfOwLj2Pks9EmXbItvwp4Gt5inzI4jey90meTDPcuCpU7MWzJyhGt4RAH69pOA7gk+iwp1QtF8g+8n395ZMwxb2QL2/cOwCYtdIpyNGDj6q6sNm7T8ypo6d+7E/pKy4OhIRwUXaV8OBl1vyy4iQ0kkxs2+s8kiQUCDqit9WH5Wy+yTbfVEVzt2SKhLltk2iFMiG2Y/NLOzij6/ocRl2MA3s33aRB3y1hkdHFGUGUjX++zp9dcMfYUHIsDLks9OOulv8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
